NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/10-10-20-151-9054-ca-org2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/10-10-20-151-9054-ca-org2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/10-10-20-151-9054-ca-org2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/10-10-20-151-9054-ca-org2.pem
    OrganizationalUnitIdentifier: orderer
