version: '3.7'
networks:
  FabricNetwork:
    external: true
    name: FabricNetwork_net
volumes:
  orderer2.exemplo.com: null
  orderer3.exemplo.com: null
  peer0.Org3.exemplo.com: null
  peer1.Org3.exemplo.com: null
  peer0.Org4.exemplo.com: null
  peer1.Org4.exemplo.com: null
services:
  orderer2.exemplo.com:
    container_name: orderer2.exemplo.com
    image: hyperledger/fabric-orderer:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7064
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7065
    - ORDERER_METRICS_PROVIDER=prometheus
    - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9213
    - ORDERER_OPERATIONS_TLS_ENABLED=false
    working_dir: /root
    command: orderer
    volumes:
    - ../organizations/ordererOrganizations/exemplo.com/orderers/orderer2.exemplo.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/exemplo.com/orderers/orderer2.exemplo.com/tls/:/var/hyperledger/orderer/tls
    - orderer2.exemplo.com:/var/hyperledger/production/orderer
    ports:
    - 7064:7064
    - 7065:7065
    - 9213:9213
    networks:
    - FabricNetwork
    extra_hosts:
    - orderer0.exemplo.com:10.10.20.151
    - orderer1.exemplo.com:10.10.20.151
    - peer0.Org1.exemplo.com:10.10.20.151
    - peer1.Org1.exemplo.com:10.10.20.151
    - peer0.Org2.exemplo.com:10.10.20.151
    - peer1.Org2.exemplo.com:10.10.20.151
    - basic_asset.channel-all:10.10.20.151
    - calc_do.channel-all:10.10.20.151
  orderer3.exemplo.com:
    container_name: orderer3.exemplo.com
    image: hyperledger/fabric-orderer:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7066
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7067
    - ORDERER_METRICS_PROVIDER=prometheus
    - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9214
    - ORDERER_OPERATIONS_TLS_ENABLED=false
    working_dir: /root
    command: orderer
    volumes:
    - ../organizations/ordererOrganizations/exemplo.com/orderers/orderer3.exemplo.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/exemplo.com/orderers/orderer3.exemplo.com/tls/:/var/hyperledger/orderer/tls
    - orderer3.exemplo.com:/var/hyperledger/production/orderer
    ports:
    - 7066:7066
    - 7067:7067
    - 9214:9214
    networks:
    - FabricNetwork
    extra_hosts:
    - orderer0.exemplo.com:10.10.20.151
    - orderer1.exemplo.com:10.10.20.151
    - peer0.Org1.exemplo.com:10.10.20.151
    - peer1.Org1.exemplo.com:10.10.20.151
    - peer0.Org2.exemplo.com:10.10.20.151
    - peer1.Org2.exemplo.com:10.10.20.151
    - basic_asset.channel-all:10.10.20.151
    - calc_do.channel-all:10.10.20.151
  peer0.Org3.exemplo.com:
    container_name: peer0.Org3.exemplo.com
    image: hyperledger/fabric-peer:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.Org3.exemplo.com
    - CORE_PEER_ADDRESS=peer0.Org3.exemplo.com:11051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    - CORE_PEER_CHAINCODEADDRESS=peer0.Org3.exemplo.com:11052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org3.exemplo.com:11051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Org3.exemplo.com:12051
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_METRICS_PROVIDER=prometheus
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9205
    - CORE_OPERATIONS_TLS_ENABLED=false
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ./peercfg:/etc/hyperledger/peercfg
    - ../organizations/peerOrganizations/Org3.exemplo.com/peers/peer0.Org3.exemplo.com:/etc/hyperledger/fabric
    - peer0.Org3.exemplo.com:/var/hyperledger/production
    - ../../builders/ccaas:/opt/hyperledger/ccaas_builder
    ports:
    - 11051:11051
    - 9205:9205
    networks:
    - FabricNetwork
    command: peer node start
    extra_hosts:
    - orderer0.exemplo.com:10.10.20.151
    - orderer1.exemplo.com:10.10.20.151
    - peer0.Org1.exemplo.com:10.10.20.151
    - peer1.Org1.exemplo.com:10.10.20.151
    - peer0.Org2.exemplo.com:10.10.20.151
    - peer1.Org2.exemplo.com:10.10.20.151
    - basic_asset.channel-all:10.10.20.151
    - calc_do.channel-all:10.10.20.151
  peer1.Org3.exemplo.com:
    container_name: peer1.Org3.exemplo.com
    image: hyperledger/fabric-peer:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.Org3.exemplo.com
    - CORE_PEER_ADDRESS=peer1.Org3.exemplo.com:12051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
    - CORE_PEER_CHAINCODEADDRESS=peer1.Org3.exemplo.com:12052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org3.exemplo.com:12051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Org3.exemplo.com:11051
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_METRICS_PROVIDER=prometheus
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9206
    - CORE_OPERATIONS_TLS_ENABLED=false
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ./peercfg:/etc/hyperledger/peercfg
    - ../organizations/peerOrganizations/Org3.exemplo.com/peers/peer1.Org3.exemplo.com:/etc/hyperledger/fabric
    - peer1.Org3.exemplo.com:/var/hyperledger/production
    - ../../builders/ccaas:/opt/hyperledger/ccaas_builder
    ports:
    - 12051:12051
    - 9206:9206
    networks:
    - FabricNetwork
    command: peer node start
    extra_hosts:
    - orderer0.exemplo.com:10.10.20.151
    - orderer1.exemplo.com:10.10.20.151
    - peer0.Org1.exemplo.com:10.10.20.151
    - peer1.Org1.exemplo.com:10.10.20.151
    - peer0.Org2.exemplo.com:10.10.20.151
    - peer1.Org2.exemplo.com:10.10.20.151
    - basic_asset.channel-all:10.10.20.151
    - calc_do.channel-all:10.10.20.151
  peer0.Org4.exemplo.com:
    container_name: peer0.Org4.exemplo.com
    image: hyperledger/fabric-peer:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.Org4.exemplo.com
    - CORE_PEER_ADDRESS=peer0.Org4.exemplo.com:13051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
    - CORE_PEER_CHAINCODEADDRESS=peer0.Org4.exemplo.com:13052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org4.exemplo.com:13051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Org4.exemplo.com:14051
    - CORE_PEER_LOCALMSPID=Org4MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_METRICS_PROVIDER=prometheus
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9207
    - CORE_OPERATIONS_TLS_ENABLED=false
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ./peercfg:/etc/hyperledger/peercfg
    - ../organizations/peerOrganizations/Org4.exemplo.com/peers/peer0.Org4.exemplo.com:/etc/hyperledger/fabric
    - peer0.Org4.exemplo.com:/var/hyperledger/production
    - ../../builders/ccaas:/opt/hyperledger/ccaas_builder
    ports:
    - 13051:13051
    - 9207:9207
    networks:
    - FabricNetwork
    command: peer node start
    extra_hosts:
    - orderer0.exemplo.com:10.10.20.151
    - orderer1.exemplo.com:10.10.20.151
    - peer0.Org1.exemplo.com:10.10.20.151
    - peer1.Org1.exemplo.com:10.10.20.151
    - peer0.Org2.exemplo.com:10.10.20.151
    - peer1.Org2.exemplo.com:10.10.20.151
    - basic_asset.channel-all:10.10.20.151
    - calc_do.channel-all:10.10.20.151
  peer1.Org4.exemplo.com:
    container_name: peer1.Org4.exemplo.com
    image: hyperledger/fabric-peer:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.Org4.exemplo.com
    - CORE_PEER_ADDRESS=peer1.Org4.exemplo.com:14051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
    - CORE_PEER_CHAINCODEADDRESS=peer1.Org4.exemplo.com:14052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org4.exemplo.com:14051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Org4.exemplo.com:13051
    - CORE_PEER_LOCALMSPID=Org4MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_METRICS_PROVIDER=prometheus
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9208
    - CORE_OPERATIONS_TLS_ENABLED=false
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ./peercfg:/etc/hyperledger/peercfg
    - ../organizations/peerOrganizations/Org4.exemplo.com/peers/peer1.Org4.exemplo.com:/etc/hyperledger/fabric
    - peer1.Org4.exemplo.com:/var/hyperledger/production
    - ../../builders/ccaas:/opt/hyperledger/ccaas_builder
    ports:
    - 14051:14051
    - 9208:9208
    networks:
    - FabricNetwork
    command: peer node start
    extra_hosts:
    - orderer0.exemplo.com:10.10.20.151
    - orderer1.exemplo.com:10.10.20.151
    - peer0.Org1.exemplo.com:10.10.20.151
    - peer1.Org1.exemplo.com:10.10.20.151
    - peer0.Org2.exemplo.com:10.10.20.151
    - peer1.Org2.exemplo.com:10.10.20.151
    - basic_asset.channel-all:10.10.20.151
    - calc_do.channel-all:10.10.20.151
