NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/10-10-20-152-11054-ca-org4.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/10-10-20-152-11054-ca-org4.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/10-10-20-152-11054-ca-org4.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/10-10-20-152-11054-ca-org4.pem
    OrganizationalUnitIdentifier: orderer
